version: 2

project_name: loglit

builds:
  - id: loglit
    main: .
    binary: loglit
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/madmaxieee/loglit/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: loglit
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  filters:
    exclude:
      - '^docs?:'
      - '^tests?:'
      - '^chore:'
      - '^Merge pull request'
      - '^Merge branch'
